<!DOCTYPE html>


<!--
 | Generated by Apache Maven Doxia Site Renderer 2.0.0-M10 from content/xdoc/download.xml.vm at 2024-02-01
 | Rendered using Apache Maven Fluido Skin 2.0.0-M6
-->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="generator" content="Apache Maven Doxia Site Renderer 2.0.0-M10" />
    <meta name="author" content="Brett Porter" />
    <meta name="author" content="Jason van Zyl" />
    <meta name="author" content="John Casey" />
    <meta name="author" content="Manfred Moser" />
    <title>Maven – Download Apache Maven</title>
    <link rel="stylesheet" href="./css/apache-maven-fluido-2.0.0-M6.min.css" />
    <link rel="stylesheet" href="./css/site.css" />
    <link rel="stylesheet" href="./css/print.css" media="print" />
    <script src="./js/apache-maven-fluido-2.0.0-M6.min.js"></script>

    <!-- Matomo -->
    <script>
        var _paq = window._paq = window._paq || [];
        _paq.push(['disableCookies']);
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);

        (function() {
            var u="https://analytics.apache.org/";
            _paq.push(['setTrackerUrl', u+'/matomo.php']);
            _paq.push(['setSiteId', '3']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.async=true; g.src=u+'/matomo.js'; s.parentNode.insertBefore(g,s);
        })();
    </script>
    <!-- End Matomo Code -->
  </head>
  <body class="topBarDisabled">
    <div class="container-fluid">
      <header>
        <div id="banner">
          <div class="pull-left"><a href="https://www.apache.org/" id="bannerLeft"><img src="images/apache-maven-project.png"  alt="Apache Maven Site" style="" /></a></div>
          <div class="pull-right"><a href="./" id="bannerRight"><img src="images/maven-logo-black-on-white.png"  alt="" style="" /></a></div>
          <div class="clear"><hr/></div>
        </div>

        <div id="breadcrumbs">
          <ul class="breadcrumb">
      <li><a href="https://www.apache.org/" class="externalLink" title="Apache">Apache</a><span class="divider">/</span></li>
      <li><a href="index.html" title="Maven">Maven</a><span class="divider">/</span></li>
    <li class="active ">Download Apache Maven <a href="https://github.com/apache/maven-site/tree/master/content/xdoc/download.xml.vm"><img src="./images/accessories-text-editor.png" title="Edit" /></a></li>
        <li id="publishDate" class="pull-right"><span class="divider">|</span> Last Published: 2024-02-01</li>
        <li class="pull-right"><span class="divider">|</span>
<a href="scm.html" title="Get Sources">Get Sources</a></li>
        <li class="pull-right"><a href="download.cgi" title="Download">Download</a></li>
          </ul>
        </div>
      </header>
      <div class="row-fluid">
        <header id="leftColumn" class="span2">
          <nav class="well sidebar-nav">
  <ul class="nav nav-list">
    <li><a href="index.html" title="Welcome"><span class="none"></span>Welcome</a></li>
    <li><a href="https://www.apache.org/licenses/" class="externalLink" title="License"><span class="none"></span>License</a></li>
   <li class="nav-header">About Maven</li>
    <li><a href="what-is-maven.html" title="What is Maven?"><span class="none"></span>What is Maven?</a></li>
    <li><a href="maven-features.html" title="Features"><span class="none"></span>Features</a></li>
    <li class="active"><a><span class="none"></span>Download</a></li>
    <li><a href="users/index.html" title="Use"><span class="icon-chevron-right"></span>Use</a></li>
    <li><a href="docs/history.html" title="Release Notes"><span class="none"></span>Release Notes</a></li>
   <li class="nav-header">Documentation</li>
    <li><a href="plugins/index.html" title="Maven Plugins"><span class="none"></span>Maven Plugins</a></li>
    <li><a href="extensions/index.html" title="Maven Extensions"><span class="none"></span>Maven Extensions</a></li>
    <li><a href="guides/index.html" title="Index (category)"><span class="none"></span>Index (category)</a></li>
    <li><a href="users/index.html" title="User Centre"><span class="icon-chevron-right"></span>User Centre</a></li>
    <li><a href="plugin-developers/index.html" title="Plugin Developer Centre"><span class="icon-chevron-right"></span>Plugin Developer Centre</a></li>
    <li><a href="repositories/index.html" title="Maven Repository Centre"><span class="icon-chevron-right"></span>Maven Repository Centre</a></li>
    <li><a href="developers/index.html" title="Maven Developer Centre"><span class="icon-chevron-right"></span>Maven Developer Centre</a></li>
    <li><a href="articles.html" title="Books and Resources"><span class="none"></span>Books and Resources</a></li>
    <li><a href="security.html" title="Security"><span class="none"></span>Security</a></li>
   <li class="nav-header">Community</li>
    <li><a href="community.html" title="Community Overview"><span class="none"></span>Community Overview</a></li>
    <li><a href="project-roles.html" title="Project Roles"><span class="none"></span>Project Roles</a></li>
    <li><a href="guides/development/guide-helping.html" title="How to Contribute"><span class="none"></span>How to Contribute</a></li>
    <li><a href="users/getting-help.html" title="Getting Help"><span class="none"></span>Getting Help</a></li>
    <li><a href="issue-management.html" title="Issue Management"><span class="none"></span>Issue Management</a></li>
    <li><a href="scm.html" title="Getting Maven Source"><span class="none"></span>Getting Maven Source</a></li>
    <li><a href="team.html" title="The Maven Team"><span class="none"></span>The Maven Team</a></li>
   <li class="nav-header">Project Documentation</li>
    <li><a href="project-info.html" title="Project Information"><span class="icon-chevron-right"></span>Project Information</a></li>
   <li class="nav-header">Maven Projects</li>
    <li><a href="ref/current" title="Maven"><span class="none"></span>Maven</a></li>
    <li><a href="archetypes/index.html" title="Archetypes"><span class="none"></span>Archetypes</a></li>
    <li><a href="extensions/index.html" title="Extensions"><span class="none"></span>Extensions</a></li>
    <li><a href="pom/index.html" title="Parent POMs"><span class="none"></span>Parent POMs</a></li>
    <li><a href="plugins/index.html" title="Plugins"><span class="none"></span>Plugins</a></li>
    <li><a href="skins/index.html" title="Skins"><span class="none"></span>Skins</a></li>
    <li><a title=""><span class="icon-chevron-down"></span></a>
     <ul class="nav nav-list">
      <li><a href="archetype/index.html" title="Archetype"><span class="none"></span>Archetype</a></li>
      <li><a href="resolver/index.html" title="Artifact Resolver"><span class="none"></span>Artifact Resolver</a></li>
      <li><a href="doxia/index.html" title="Doxia"><span class="none"></span>Doxia</a></li>
      <li><a href="maven-indexer/index.html" title="Indexer"><span class="none"></span>Indexer</a></li>
      <li><a href="jxr/index.html" title="JXR"><span class="none"></span>JXR</a></li>
      <li><a href="plugin-testing/index.html" title="Plugin Testing"><span class="none"></span>Plugin Testing</a></li>
      <li><a href="plugin-tools/index.html" title="Plugin Tools"><span class="none"></span>Plugin Tools</a></li>
      <li><a href="apache-resource-bundles/index.html" title="Resource Bundles"><span class="none"></span>Resource Bundles</a></li>
      <li><a href="scm/index.html" title="SCM"><span class="none"></span>SCM</a></li>
      <li><a href="shared/index.html" title="Shared Components"><span class="none"></span>Shared Components</a></li>
      <li><a href="surefire/index.html" title="Surefire"><span class="none"></span>Surefire</a></li>
      <li><a href="wagon/index.html" title="Wagon"><span class="none"></span>Wagon</a></li>
     </ul></li>
   <li class="nav-header">ASF</li>
    <li><a href="https://www.apache.org/foundation/how-it-works.html" class="externalLink" title="How Apache Works"><span class="none"></span>How Apache Works</a></li>
    <li><a href="https://www.apache.org/foundation/" class="externalLink" title="Foundation"><span class="none"></span>Foundation</a></li>
    <li><a href="https://privacy.apache.org/policies/privacy-policy-public.html" class="externalLink" title="Data Privacy"><span class="none"></span>Data Privacy</a></li>
    <li><a href="https://www.apache.org/foundation/sponsorship.html" class="externalLink" title="Sponsoring Apache"><span class="none"></span>Sponsoring Apache</a></li>
    <li><a href="https://www.apache.org/foundation/thanks.html" class="externalLink" title="Thanks"><span class="none"></span>Thanks</a></li>
  </ul>
          </nav>
          <div class="well sidebar-nav">
            <div id="poweredBy">
              <div class="clear"></div>
              <div class="clear"></div>
              <div class="clear"></div>
<a href="http://maven.apache.org/" title="Built by Maven" class="poweredBy"><img class="builtBy" alt="Built by Maven" src="./images/logos/maven-feather.png" /></a>
            </div>
          </div>
        </header>
        <main id="bodyColumn"  class="span10" >

  
    <section>
<h1>Downloading Apache Maven 3.9.6</h1>

      
<p>Apache Maven 3.9.6 is the latest release: it is the recommended version for all users.</p>

      
      <a id="Requirements"></a><section id="Requirements">
<h2>System Requirements</h2>
        
<p>
          </p>
<table class="table table-striped">
            
<tr class="a">
              
<td><b>Java Development Kit (JDK)</b></td>
              
<td>Maven 3.9+ requires JDK 8 or above to execute. It still allows you to build against 1.3 and other JDK versions
              <a href="/guides/mini/guide-using-toolchains.html">by using toolchains</a>.</td>
            </tr>
            
<tr class="b">
              
<td><b>Memory</b></td>
              
<td>No minimum requirement</td>
            </tr>
            
<tr class="a">
              
<td><b>Disk</b></td>
              
<td>Approximately 10MB is required for the Maven installation itself. In addition to that, disk space will
              be used for your local Maven repository. The size of your local repository will vary depending on usage but expect at
              least 500MB.</td>
            </tr>
            
<tr class="b">
              
<td><b>Operating System</b></td>
              
<td>No minimum requirement. Start up scripts are included as shell scripts (tested on many Unix flavors) and Windows batch files.</td>
            </tr>
          </table>
        
      </section>

      <section>
<h2>Files</h2>
      
<p>Maven is distributed in several formats for your convenience. Simply pick a 
      ready-made binary distribution archive and follow the <a href="./install.html">
      installation instructions.</a>
      Use a source archive if you intend to build Maven yourself.</p>
      
<p>
      In order to guard against corrupted downloads/installations, it is highly recommended to
      <a href="https://www.apache.org/info/verification.html" class="externalLink">verify the signature</a>
      of the release bundles against the public <a href="https://downloads.apache.org/maven/KEYS" class="externalLink">KEYS</a> used by the Apache Maven
      developers.</p>
      
<table class="table table-striped">
        <thead>
          
<tr class="a">
            
<th></th>
            
<th>Link</th>
            
<th>Checksums</th>
            
<th>Signature</th>
          </tr>
        </thead>
        <tbody>
          
<tr class="b">
            
<td>Binary tar.gz archive</td>
            
<td><a href="https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz">apache-maven-3.9.6-bin.tar.gz</a></td>
            
<td><a href="https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz.sha512" class="externalLink">apache-maven-3.9.6-bin.tar.gz.sha512</a></td>
            
<td><a href="https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz.asc" class="externalLink">apache-maven-3.9.6-bin.tar.gz.asc</a></td>
          </tr>
          
<tr class="a">
            
<td>Binary zip archive</td>
            
<td><a href="https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip">apache-maven-3.9.6-bin.zip</a></td>
            
<td><a href="https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip.sha512" class="externalLink">apache-maven-3.9.6-bin.zip.sha512</a></td>
            
<td><a href="https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip.asc" class="externalLink">apache-maven-3.9.6-bin.zip.asc</a></td>
          </tr>
          
<tr class="b">
            
<td>Source tar.gz archive</td>
            
<td><a href="https://dlcdn.apache.org/maven/maven-3/3.9.6/source/apache-maven-3.9.6-src.tar.gz">apache-maven-3.9.6-src.tar.gz</a></td>
            
<td><a href="https://downloads.apache.org/maven/maven-3/3.9.6/source/apache-maven-3.9.6-src.tar.gz.sha512" class="externalLink">apache-maven-3.9.6-src.tar.gz.sha512</a></td>
            
<td><a href="https://downloads.apache.org/maven/maven-3/3.9.6/source/apache-maven-3.9.6-src.tar.gz.asc" class="externalLink">apache-maven-3.9.6-src.tar.gz.asc</a>
            </td>
          </tr>
          
<tr class="a">
            
<td>Source zip archive </td>
            
<td><a href="https://dlcdn.apache.org/maven/maven-3/3.9.6/source/apache-maven-3.9.6-src.zip">apache-maven-3.9.6-src.zip</a></td>
            
<td><a href="https://downloads.apache.org/maven/maven-3/3.9.6/source/apache-maven-3.9.6-src.zip.sha512" class="externalLink">apache-maven-3.9.6-src.zip.sha512</a></td>
            
<td><a href="https://downloads.apache.org/maven/maven-3/3.9.6/source/apache-maven-3.9.6-src.zip.asc" class="externalLink">apache-maven-3.9.6-src.zip.asc</a></td>
          </tr>
        </tbody>
      </table>
      
<ul>
        
<li>3.9.6 <a href="./docs/3.9.6/release-notes.html">Release Notes</a> and
            <a href="./ref/3.9.6/">Release Reference Documentation</a></li>
        
<li><a href="./scm.html">latest source code from source repository</a></li>
        
<li>Distributed under the <a href="https://www.apache.org/licenses/" class="externalLink">Apache License, version 2.0</a></li>
        
<li>other:
<ul>
        
<li><a href="./maven-site-1.0-site.jar">Apache Maven Website As Documentation Archive</a></li>
        
        
<li><a href="https://dlcdn.apache.org/maven/">All current release sources (plugins, shared libraries,...) available at https://downloads.apache.org/maven/</a></li>
        </ul></li>
      </ul>
      </section>

    </section>

    <section>
<h1>Other Releases</h1>
      
<p>It is strongly recommended to use the latest release version of Apache Maven to take advantage of newest features and bug fixes.</p>
      
      
<p>If you still want to use an old version, you can find more information in the
      <a href="./docs/history.html">Maven Releases History</a> and can download files from 
      the  <a href="https://archive.apache.org/dist/maven/maven-3/" class="externalLink">Maven 3 archives</a> for versions 3.0.4+
      and <a href="https://archive.apache.org/dist/maven/binaries/" class="externalLink">legacy archives</a> for earlier releases.</p>

      <section>
<h2>Previous Stable 3.8.x Release</h2>
        
<p>Apache Maven 3.8.8 is the previous stable minor release for all users.</p>
        
<p>
          </p>
<table class="table table-striped">
            
<tr class="a">
              
<td><b>Java Development Kit (JDK)</b></td>
              
<td>Maven 3.8+ requires JDK 1.7 or above to execute. It still allows you to build against 1.3 and other JDK versions
                  <a href="/guides/mini/guide-using-toolchains.html">by using toolchains</a>.</td>
            </tr>
          </table>
        
        
<p>Maven is distributed in several formats for your convenience. Simply pick a
              ready-made binary distribution archive and follow the <a href="./install.html">
              installation instructions.</a>
              Use a source archive if you intend to build Maven yourself.</p>
        
<p>
            In order to guard against corrupted downloads/installations, it is highly recommended to
              <a href="https://www.apache.org/info/verification.html" class="externalLink">verify the signature</a>
              of the release bundles against the public <a href="https://downloads.apache.org/maven/KEYS" class="externalLink">KEYS</a> used by the Apache Maven
              developers.</p>
        
<table class="table table-striped">
          <thead>
            
<tr class="a">
              
<th>Format</th>
              
<th>Binary (Checksum, Signature)</th>
              
<th>Source (Checksum, Signature)</th>
            </tr>
          </thead>
          <tbody>
            
<tr class="b">
              
<td>tar.gz archives</td>
              
<td>Binary <a href="https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz">apache-maven-3.8.8-bin.tar.gz</a>
                  (<a href="https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz.sha512" class="externalLink">sha512</a>, 
                   <a href="https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz.asc" class="externalLink">asc</a>)</td>
              
<td>Source <a href="https://dlcdn.apache.org/maven/maven-3/3.8.8/source/apache-maven-3.8.8-src.tar.gz">apache-maven-3.8.8-src.tar.gz</a>
                  (<a href="https://downloads.apache.org/maven/maven-3/3.8.8/source/apache-maven-3.8.8-src.tar.gz.sha512" class="externalLink">sha512</a>, 
                   <a href="https://downloads.apache.org/maven/maven-3/3.8.8/source/apache-maven-3.8.8-src.tar.gz.asc" class="externalLink">asc</a>)</td>
            </tr>
            
<tr class="a">
              
<td>zip archives</td>
              
<td>Binary <a href="https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip">apache-maven-3.8.8-bin.zip</a>
                  (<a href="https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip.sha512" class="externalLink">sha512</a>,
                   <a href="https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip.asc" class="externalLink">asc</a>)</td>
              
<td>Source <a href="https://dlcdn.apache.org/maven/maven-3/3.8.8/source/apache-maven-3.8.8-src.zip">apache-maven-3.8.8-src.zip</a>
                  (<a href="https://downloads.apache.org/maven/maven-3/3.8.8/source/apache-maven-3.8.8-src.zip.sha512" class="externalLink">sha512</a>,
                   <a href="https://downloads.apache.org/maven/maven-3/3.8.8/source/apache-maven-3.8.8-src.zip.asc" class="externalLink">asc</a>)</td>
            </tr>
          </tbody>
        </table>
        
<ul>
          
<li>3.8.8 <a href="./docs/3.8.8/release-notes.html">Release Notes</a> and
              <a href="./ref/3.8.8/">Release Reference Documentation</a></li>
          
<li>Distributed under the <a href="https://www.apache.org/licenses/" class="externalLink">Apache License, version 2.0</a></li>
        </ul>
      </section>

      <section>
<h2>Alpha 4.x Release</h2>
        
<p>Maven 4.x is currently under development, so while we are encouraging users to try it and report any issue, it is NOT safe for production use.</p>

        
<p>
          </p>
<table class="table table-striped">
            
<tr class="a">
              
<td><b>Java Development Kit (JDK)</b></td>
              
<td>Maven 4.0+ requires JDK 1.8 or above to execute. It still allows you to build against 1.3 and other JDK versions
                  <a href="/guides/mini/guide-using-toolchains.html">by using toolchains</a>.</td>
            </tr>
          </table>
        

        
<p>Maven is distributed in several formats for your convenience. Simply pick a
              ready-made binary distribution archive and follow the <a href="./install.html">
              installation instructions.</a>
              Use a source archive if you intend to build Maven yourself.</p>
        
<p>
            In order to guard against corrupted downloads/installations, it is highly recommended to
              <a href="https://www.apache.org/info/verification.html" class="externalLink">verify the signature</a>
              of the release bundles against the public <a href="https://downloads.apache.org/maven/KEYS" class="externalLink">KEYS</a> used by the Apache Maven
              developers.</p>
        
<table class="table table-striped">
          <thead>
            
<tr class="a">
              
<th>Format</th>
              
<th>Binary (Checksum, Signature)</th>
              
<th>Source (Checksum, Signature)</th>
            </tr>
          </thead>
          <tbody>
            
<tr class="b">
              
<td>tar.gz archives</td>
              
<td>Binary <a href="https://dlcdn.apache.org/maven/maven-4/4.0.0-alpha-12/binaries/apache-maven-4.0.0-alpha-12-bin.tar.gz">apache-maven-4.0.0-alpha-12-bin.tar.gz</a>
                  (<a href="https://downloads.apache.org/maven/maven-4/4.0.0-alpha-12/binaries/apache-maven-4.0.0-alpha-12-bin.tar.gz.sha512" class="externalLink">sha512</a>, 
                   <a href="https://downloads.apache.org/maven/maven-4/4.0.0-alpha-12/binaries/apache-maven-4.0.0-alpha-12-bin.tar.gz.asc" class="externalLink">asc</a>)</td>
              
<td>Source <a href="https://dlcdn.apache.org/maven/maven-4/4.0.0-alpha-12/source/apache-maven-4.0.0-alpha-12-src.tar.gz">apache-maven-4.0.0-alpha-12-src.tar.gz</a>
                  (<a href="https://downloads.apache.org/maven/maven-4/4.0.0-alpha-12/source/apache-maven-4.0.0-alpha-12-src.tar.gz.sha512" class="externalLink">sha512</a>, 
                   <a href="https://downloads.apache.org/maven/maven-4/4.0.0-alpha-12/source/apache-maven-4.0.0-alpha-12-src.tar.gz.asc" class="externalLink">asc</a>)</td>
            </tr>
            
<tr class="a">
              
<td>zip archives</td>
              
<td>Binary <a href="https://dlcdn.apache.org/maven/maven-4/4.0.0-alpha-12/binaries/apache-maven-4.0.0-alpha-12-bin.zip">apache-maven-4.0.0-alpha-12-bin.zip</a>
                  (<a href="https://downloads.apache.org/maven/maven-4/4.0.0-alpha-12/binaries/apache-maven-4.0.0-alpha-12-bin.zip.sha512" class="externalLink">sha512</a>,
                   <a href="https://downloads.apache.org/maven/maven-4/4.0.0-alpha-12/binaries/apache-maven-4.0.0-alpha-12-bin.zip.asc" class="externalLink">asc</a>)</td>
              
<td>Source <a href="https://dlcdn.apache.org/maven/maven-4/4.0.0-alpha-12/source/apache-maven-4.0.0-alpha-12-src.zip">apache-maven-4.0.0-alpha-12-src.zip</a>
                  (<a href="https://downloads.apache.org/maven/maven-4/4.0.0-alpha-12/source/apache-maven-4.0.0-alpha-12-src.zip.sha512" class="externalLink">sha512</a>,
                   <a href="https://downloads.apache.org/maven/maven-4/4.0.0-alpha-12/source/apache-maven-4.0.0-alpha-12-src.zip.asc" class="externalLink">asc</a>)</td>
            </tr>
          </tbody>
        </table>
        
<ul>
          
<li>4.0.0-alpha-12 <a href="./docs/4.0.0-alpha-12/release-notes.html">Release Notes</a> and
              <a href="./ref/4.0.0-alpha-12/">Release Reference Documentation</a></li>
          
<li>Distributed under the <a href="https://www.apache.org/licenses/" class="externalLink">Apache License, version 2.0</a></li>
          
<li><a href="https://archive.apache.org/dist/maven/maven-4/" class="externalLink">Maven 4 archives</a> for older 4.x releases.</li>
        </ul>
      </section>
    </section>
  

        </main>
      </div>
    </div>
    <hr/>
    <footer>
      <div class="container-fluid">
        <div class="row-fluid">
            <p>©      2002–2024
<a href="https://www.apache.org/">The Apache Software Foundation</a>
</p>
        </div>
      </div>
    </footer>
<script>
  if(anchors) {
    anchors.add();
  }
</script>
  </body>
</html>